// Solar Analysis PDF Generator
export function generateSolarPDF(result, lat, lng) {
  const doc = window.jspdf ? new window.jspdf.jsPDF() : new (window.jsPDF || window.jspdf.jsPDF)();
  doc.setFontSize(18);
  doc.text('GeoCortex Solar Intelligence Report', 20, 20);
  doc.setFontSize(12);
  doc.text(`Location: ${lat.toFixed(6)}, ${lng.toFixed(6)}`, 20, 35);
  doc.text('Analysis: High-Potential Areas Identified', 20, 45);
  doc.text(`Total Energy (kWh): ${result.yearlyKwh}`, 20, 60);
  doc.text(`Installation Cost (₹): ${result.installCost.toLocaleString()}`, 20, 70);
  doc.text(`Annual Savings (₹): ${result.annualSavings.toLocaleString()}`, 20, 80);
  doc.text(`Break-even Years: ${result.breakEven.toFixed(1)}`, 20, 90);
  doc.setFontSize(10);
  doc.text('Generated by GeoCortex AI', 20, 120);
  doc.save('Solar_Analysis_Report.pdf');
}
import { jsPDF } from 'jspdf';

const GOOGLE_MAPS_API_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY || 'AIzaSyB6KRRVrmndX4vPTdg36u3qU2r1MFfmI6X8';

// Clean text from emojis
const cleanEmojis = (text) => {
  return text.replace(/[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\uFE0F]|[\u{1F1E6}-\u{1F1FF}]/gu, '');
};

// Robust image fetch with error logging
const fetchImageAsBase64 = async (url) => {
  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (err) {
    console.error('Failed to fetch map image:', err);
    return null;
  }
};

export const generatePDF = async (analysisText, location, mapImage, chatMessages = [], analysisView = null) => {
  const doc = new jsPDF();
  let y = 25;

  // Helper for page breaks
  const checkPageBreak = (neededSpace) => {
    if (y + neededSpace > 275) {
      doc.addPage();
      y = 25;
    }
  };

  // ========== HEADER ==========
  doc.setFillColor(6, 182, 212);
  doc.rect(0, 0, 210, 35, 'F');

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text("GeoCortex AI Analysis Report", 105, 18, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleString()}  |  Source: Landsat 9`, 105, 28, { align: "center" });

  y = 50;

  // ========== MAP SECTION ==========
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 59);
  doc.text("Location Overview", 20, y);
  y += 8;

  let finalMapImage = null;
  if (mapImage && mapImage.startsWith('data:image')) {
    finalMapImage = mapImage;
  } else if (location || analysisView) {
    const lat = analysisView?.lat || location.lat;
    const lng = analysisView?.lng || location.lng;
    const zoom = analysisView?.zoom || 14;
    const mapUrl = `https://maps.googleapis.com/maps/api/staticmap?center=${lat},${lng}&zoom=${zoom}&size=600x300&maptype=satellite&markers=color:red%7C${location?.lat || lat},${location?.lng || lng}&key=${GOOGLE_MAPS_API_KEY}`;
    finalMapImage = await fetchImageAsBase64(mapUrl);
  }

  if (finalMapImage) {
    try {
      // Map with subtle border
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.5);
      doc.rect(20, y, 170, 75);
      doc.addImage(finalMapImage, 'JPEG', 20, y, 170, 75);
      y += 78;

      if (location) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(120);
        doc.text(`Lat: ${location.lat.toFixed(5)}  |  Lng: ${location.lng.toFixed(5)}`, 20, y);
        y += 12;
      }
    } catch (e) {
      doc.setTextColor(200, 0, 0);
      doc.setFontSize(9);
      doc.text("Map image could not be loaded.", 20, y);
      y += 15;
    }
  } else {
    doc.setTextColor(150);
    doc.setFontSize(9);
    doc.text("Map unavailable.", 20, y);
    y += 15;
  }

  // ========== EXTRACT DATA ==========
  const extractValueAfterLabel = (html, label) => {
    if (!html) return null;
    const labelIdx = html.indexOf(label);
    if (labelIdx === -1) return null;
    const afterLabel = html.substring(labelIdx);
    const match = afterLabel.match(/<\/div>\s*<div[^>]*>(.*?)<\/div>/);
    return match ? match[1].replace(/<[^>]+>/g, '').trim() : null;
  };

  const locationName = extractValueAfterLabel(analysisText, '📍 Location:') || "Unknown Location";
  const temperature = extractValueAfterLabel(analysisText, '🔥 Land Surface Temperature:') || "N/A";

  let insights = "";
  const insightsIdx = analysisText?.indexOf('🤖 AI Insights:') ?? -1;
  if (insightsIdx !== -1) {
    let rawInsights = analysisText.substring(insightsIdx);
    rawInsights = rawInsights.replace(/<div[^>]*>.*?AI Insights:.*?<\/div>/, '');
    rawInsights = rawInsights.replace(/<br\s*\/?>/gi, '\n');
    insights = rawInsights.replace(/<[^>]+>/g, '');
    const tempEl = document.createElement('div');
    tempEl.innerHTML = insights;
    insights = (tempEl.textContent || tempEl.innerText || '').trim();
  }

  // ========== THERMAL DATA CARD ==========
  checkPageBreak(50);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 59);
  doc.text("Thermal Analysis Summary", 20, y);
  y += 10;

  // Card background
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(20, y, 170, 35, 3, 3, 'F');

  // Left column - Location
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("LOCATION", 28, y + 10);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  const locText = doc.splitTextToSize(locationName, 80);
  doc.text(locText[0], 28, y + 20);

  // Right column - Temperature
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("SURFACE TEMPERATURE", 115, y + 10);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(234, 88, 12); // Orange
  doc.text(temperature, 115, y + 22);

  y += 50;

  // ========== AI INSIGHTS ==========
  if (insights && insights.length > 10) {
    checkPageBreak(60);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(30, 41, 59);
    doc.text("AI Consultant Insights", 20, y);
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(55, 65, 81);

    const cleanedInsights = cleanEmojis(insights).trim();
    const lines = doc.splitTextToSize(cleanedInsights, 170);

    for (let i = 0; i < lines.length; i++) {
      checkPageBreak(6);
      doc.text(lines[i], 20, y);
      y += 5.5;
    }
    y += 10;
  }

  // ========== CHAT HISTORY ==========
  if (chatMessages && chatMessages.length > 0) {
    checkPageBreak(40);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(30, 41, 59);
    doc.text("Conversation Log", 20, y);
    y += 12;

    chatMessages.forEach((msg) => {
      checkPageBreak(20);

      const isUser = msg.role === 'user';

      // Role label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(isUser ? 100 : 6, isUser ? 116 : 182, isUser ? 139 : 212);
      doc.text(isUser ? 'You' : 'Gemini AI', 20, y);
      y += 5;

      // Message content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      const msgText = cleanEmojis(msg.text || '');
      const wrapped = doc.splitTextToSize(msgText, 165);

      wrapped.forEach((line) => {
        checkPageBreak(5);
        doc.text(line, 25, y);
        y += 4.5;
      });
      y += 6;
    });
  }

  // ========== FOOTER ON ALL PAGES ==========
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(220);
    doc.line(20, 282, 190, 282);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(140);
    doc.text(`Page ${i} of ${pageCount}`, 20, 288);
    doc.text("GeoCortex Command Center  •  Confidential", 190, 288, { align: "right" });
  }

  doc.save('GeoCortex_Report.pdf');
};

export const generatePlanningPDF = async (data, mapImage) => {
  const doc = new jsPDF();
  let y = 20;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(6, 182, 212);
  doc.text("URBAN PLANNING & IMPACT REPORT", 105, y, { align: "center" });
  y += 15;

  // Metadata
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, y);
  y += 6;
  doc.text("Source: GeoCortex Planning Simulation Engine", 20, y);
  y += 10;

  // Line
  doc.setDrawColor(6, 182, 212);
  doc.setLineWidth(0.5);
  doc.line(20, y, 190, y);
  y += 15;

  // 1. Snapshot
  if (mapImage) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("1. Planned Layout Snapshot", 20, y);
    y += 10;
    try {
      doc.addImage(mapImage, 'PNG', 20, y, 170, 95); // reduced height slightly
      y += 105;
    } catch (err) {
      console.error("Error adding map image to PDF", err);
      doc.text("(Map Snapshot Unavailable)", 20, y);
      y += 20;
    }
  }

  // 2. Executive Summary - Impact Table
  if (y > 220) { doc.addPage(); y = 20; }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("2. Executive Impact Summary", 20, y);
  y += 10;

  // Draw a summary box
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(20, y, 170, 45, 3, 3, 'F');

  doc.setFontSize(11);
  doc.setTextColor(60);
  doc.text("Net Temperature Change:", 30, y + 24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14); // Slightly larger for emphasis

  const change = data.net_change || 0;
  const color = change < 0 ? [34, 197, 94] : (change > 0 ? [239, 68, 68] : [100, 116, 139]);
  doc.setTextColor(...color);
  doc.text(`${change > 0 ? '+' : ''}${change.toFixed(2)} °C`, 140, y + 24);

  y += 60;

  // 3. Infrastructure Breakdown
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("3. Infrastructure Breakdown", 20, y);
  y += 10;

  const items = data.item_summary || {};
  let xOffset = 20;
  Object.entries(items).forEach(([key, count]) => {
    doc.setFillColor(240, 249, 255);
    doc.rect(xOffset, y, 40, 25, 'F');
    doc.setFontSize(16);
    doc.setTextColor(6, 182, 212);
    doc.text(count.toString(), xOffset + 20, y + 12, { align: 'center' });
    doc.setFontSize(9);
    doc.setTextColor(80);
    doc.text(key, xOffset + 20, y + 20, { align: 'center' });
    xOffset += 50;
  });
  y += 40;

  // 4. AI Consultant Insights (Cleaned)
  if (y > 220) { doc.addPage(); y = 20; }

  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("4. AI Consultant Analysis", 20, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const aiText = data.ai_report_text || "No insights available.";
  const cleanText = cleanEmojis(aiText); // Remove emojis for PDF
  const lines = cleanText.split('\n').filter(l => l.trim().length > 0);

  lines.forEach(line => {
    if (y > 270) { doc.addPage(); y = 20; }

    // Check for bold markers from AI **text**
    if (line.includes('**')) {
      line = line.replace(/\*\*/g, '');
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFont("helvetica", "normal");
    }

    // Check for headers (numbered items)
    if (line.match(/^\d+\./)) {
      y += 4;
      doc.setFont("helvetica", "bold");
    }

    const wrapped = doc.splitTextToSize(line, 170);
    doc.text(wrapped, 20, y);
    y += wrapped.length * 5 + 2;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("CONFIDENTIAL - GEOCORTEX URBAN PLANNING SIMULATION", 105, 285, { align: "center" });

  doc.save('GeoCortex_Planning_Report.pdf');
};